site_name: Monitoring probes [V1]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/monitoring-probes
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2020 SRCE

nav:
- Basic Information:
    - Home: index.md
- Monitoring Probes:
    - Guidelines for monitoring probes: guidelines_for_monitoring_probes.md

theme: readthedocs
